version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    assignees:
      - "wintero92"
    commit-message:
      prefix: "build: update dependencies\n\n"
      prefix-development: "build: update development dependencies\n\n"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    assignees:
      - "wintero92"
    commit-message:
      prefix: "ci: update dependencies\n\n"
      include: "scope"