indent-width = 4
line-length = 120
target-version = "py312"

lint.select = ["ALL"]
lint.ignore = [
    # "D100",
    # "D104",
    # "D211",
    # "D213",
    # "D417",
    "D100",
    "D211",
    "D213",
    "D417",
    "INP001"
]